### ISSUE TITLE
Author biography text

### ISSUE THREAD

**Issue by Shambla** [Shambla/guitar#1]
One or two paragraphs.

**Comment by Rustyribcage** [comment]
Mr. Streckfus has been studying music in college level institutions for eight years and holds an Associate of Arts of Music from Harford Community College and a Bachelors in Classical Guitar Performance from Peabody Conservatory of the Johns Hopkins University. 

	Brian’s former teachers include Ray Chester, a former student of Aaron Shearer, head chairman of guitar at Peabody Conservatory and one of the world’s leading guitar pedagogues. Brian has also received music instruction from other well trained guitarists in the Maryland region such as Peabody Alumni, James Hontz, Ph D. and jazz guitarists Brian Kooken and Vincent Corson.  

	Brian has performed jazz, popular and classical genres at Maryland music venues such as Baltimore’s Lyric Opera House, Miriam A. Friedberg Concert Hall, The Recher Theatre, Fret Fest at Goodwin Hall, Cohen-Davison Family Theatre, Fallston Hall, and Fletcher’s. 
	
	Brian also has a home recording studio and has produced over seventy music related videos that are viewed worldwide. The purposes of the videos include entertainment, music pedagogy and music therapy. 

	Brian has been teaching privately for three years and currently teaches at Music & Arts. Brian’s extensive formal training in combination with an undogmatic, best-of-both-worlds jazz and classical modern approach, diverse repertoire and music technology skills make him an excellent music instructor.

**Comment by Rustyribcage** [comment]
Mr. Streckfus has been studying music in college level institutions for eight years and holds an Associate of Arts of Music from Harford Community College and a Bachelors in Classical Guitar Performance from Peabody Conservatory of the Johns Hopkins University. 

	Brian’s former teachers include Ray Chester, a former student of Aaron Shearer, head chairman of guitar at Peabody Conservatory and one of the world’s leading guitar pedagogues. Brian has also received music instruction from other well trained guitarists in the Maryland region such as Peabody Alumni, James Hontz, Ph D. and jazz guitarists Brian Kooken and Vincent Corson.  

	Brian has performed jazz, popular and classical genres at Maryland music venues such as Baltimore’s Lyric Opera House, Miriam A. Friedberg Concert Hall, The Recher Theatre, Fret Fest at Goodwin Hall, Cohen-Davison Family Theatre, Fallston Hall, and Fletcher’s. 
	
	Brian also has a home recording studio and has produced over seventy music related videos that are viewed worldwide. The purposes of the videos include entertainment, music pedagogy and music therapy. 

	Brian has been teaching privately for three years and currently teaches at Music & Arts. Brian’s extensive formal training in combination with an undogmatic, best-of-both-worlds jazz and classical modern approach, diverse repertoire and music technology skills make him an excellent music instructor.

**Comment by Rustyribcage** [comment]
Mr. Streckfus has been studying music in college level institutions for eight years and holds an Associate of Arts of Music from Harford Community College and a Bachelors in Classical Guitar Performance from Peabody Conservatory of the Johns Hopkins University. 

Brian’s former teachers include Ray Chester, a former student of Aaron Shearer, head chairman of guitar at Peabody Conservatory and one of the world’s leading guitar pedagogues. Brian has also received music instruction from other well trained guitarists in the Maryland region such as Peabody Alumni, James Hontz, Ph D. and jazz guitarists Brian Kooken and Vincent Corson.  

Brian has performed jazz, popular and classical genres at Maryland music venues such as Baltimore’s Lyric Opera House, Miriam A. Friedberg Concert Hall, The Recher Theatre, Fret Fest at Goodwin Hall, Cohen-Davison Family Theatre, Fallston Hall, and Fletcher’s. 
	
Brian also has a home recording studio and has produced over seventy music related videos that are viewed worldwide. The purposes of the videos include entertainment, music pedagogy and music therapy. 

	Brian has been teaching privately for three years and currently teaches at Music & Arts. Brian’s extensive formal training in combination with an undogmatic, best-of-both-worlds jazz and classical modern approach, diverse repertoire and music technology skills make him an excellent music instructor.

**Comment by Rustyribcage** [comment]
Mr. Streckfus has been studying music in college level institutions for eight years and holds an Associate of Arts of Music from Harford Community College and a Bachelors in Classical Guitar Performance from Peabody Conservatory of the Johns Hopkins University. 

Brian’s former teachers include Ray Chester, a former student of Aaron Shearer, head chairman of guitar at Peabody Conservatory and one of the world’s leading guitar pedagogues. Brian has also received music instruction from other well trained guitarists in the Maryland region such as Peabody Alumni, James Hontz, Ph D. and jazz guitarists Brian Kooken and Vincent Corson.  

Brian has performed jazz, popular and classical genres at Maryland music venues such as Baltimore’s Lyric Opera House, Miriam A. Friedberg Concert Hall, The Recher Theatre, Fret Fest at Goodwin Hall, Cohen-Davison Family Theatre, Fallston Hall, and Fletcher’s. 

Brian also has a home recording studio and has produced over seventy music related videos that are viewed worldwide. The purposes of the videos include entertainment, music pedagogy and music therapy. 

Brian has been teaching privately for three years and currently teaches at Music & Arts. Brian’s extensive formal training in combination with an undogmatic, best-of-both-worlds jazz and classical modern approach, diverse repertoire and music technology skills make him an excellent music instructor.
