### ISSUE TITLE
Author Performances Section

### ISSUE THREAD

**Issue by Shambla** [Shambla/guitar#2]
Need to know dates/events for past performances.

**Comment by Rustyribcage** [comment]
Notable Solo Performances
Solo Guitar Recital, Fallston Hall, Bel Air, MD.    2009
           Works by: J. S. Bach
Solo Guitar Recital, Cohen-Davison Family Theatre, Baltimore, MD.   2014
           Works by: Milán, J. S. Bach, Tárrega, Ponce
Solo Guitar Recital, Cohen-Davison Family Theatre, Baltimore, MD.   2015
           Works by: Milán, J. S. Bach, Tárrega, Ponce, Villa-Lobos   

Chamber Music Performances
Classical Guitar Duo, Andie Musik, Baltimore, MD.                                                                                      2008
           Works by: W. A. Mozart
Classical Guitar Trio, Goodwin Hall (Fret-Fest) Baltimore, MD.                                                                                     2012
           Works by: J. F. Handel

Large Ensemble Experience 
Bass Section Singer, Peabody/Hopkins Chorus, Baltimore, MD  2011-2013
          Works by: Carl Orff, Leonard Bernstein, Franz Schubert, Guiseppe Verdi
Guitarist, Harford Community College Jazz Big Band, Fallston Hall, Bel Air, MC        2007-2009
          Jazz standards such as: Autumn Leaves, Anthropology, Maiden Voyage, Lush Life
