### ISSUE TITLE
Need a higher resolution version of this image

### ISSUE THREAD

**Issue by Shambla** [Shambla/guitar#3]
http://i.imgur.com/YfiHeV1.jpg

**Comment by Rustyribcage** [comment]
![11081021_10204275350103946_2984077937836021448_n](https://cloud.githubusercontent.com/assets/16448906/12049295/50054814-aeb3-11e5-86e9-99474dea2da3.jpg)

667X960

**Comment by Rustyribcage** [comment]
![11081021_10204275350103946_2984077937836021448_n cropped](https://cloud.githubusercontent.com/assets/16448906/12049312/860dc454-aeb3-11e5-8fae-b9ee4c01b96b.jpg)

658 x 1148 (hopefully this will cheat the system)

Caption: Solo Guitar Recital, Cohen-Davison Family Theatre, Baltimore, MD. 2015
Works by: Milán, J. S. Bach, Tárrega, Ponce, Villa-Lobos

**Comment by Rustyribcage** [comment]
[Website photos.zip](https://github.com/Shambla/guitar/files/74748/Website.photos.zip)

Photo archive as of Dec, 30 2015
